import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "./lib/utils";
import { baseFonts } from "./lib/fonts";
import { WebsocketProvider } from "./components/WebsocketContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(baseFonts.variable, "font-sans")}>
        <WebsocketProvider>{children}</WebsocketProvider>
      </body>
    </html>
  );
}
